title="sdf lcls impact"
title="sdf lcls impact"

[machine]
host="mcc-simul"
workdir="/sdf/group/ard/impact/output"
summary_output_dir="/sdf/group/ard/impact/output/summary"
archive_dir="/sdf/group/ard/impact/output/archive"
snapshot_dir="/sdf/group/ard/impact/output/snapshot"
mpi_run_cmd="mpirun -n {n} --use-hwthread-cpus {command_mpi}"
command="/sdf/group/ard/impact/bin/ImpactTexe"
command_mpi="/sdf/group/ard/impact/bin/ImpactTexe-mpi"
num_procs=32

[impact]
model="cu_inj"
timeout=10000
"header:Nx"=32
"header:Ny"=32
"header:Nz"=32
stop=16.5
name="lume-impact-live-demo-cu-inj"

[distgen]
"distgen:t_dist:length:value"=6.6
"distgen:n_particle"=100000
distgen_input_file="/sdf/group/ard/impact/lcls-lattice/distgen/models/cu_inj/vcc_image/distgen.yaml"
distgen_laser_file="/sdf/group/ard/impact/output/distgen_laser.txt"